selmag:
  services:
    catalogue:
      uri: http://localhost:8081
      username: catalogue_service_user
      password: password
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/manager
    username: manager
    password: manager
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/selmag
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: u7weNXboXAXsU2eOhmLHbtjZYBRn4zEu
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt
  jpa:
    show-sql: true